// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createRow = `-- name: CreateRow :exec
INSERT INTO notes (name, val, month, year)
VALUES (?, ?, ?, ?)
`

type CreateRowParams struct {
	Name  string
	Val   int64
	Month int64
	Year  int64
}

func (q *Queries) CreateRow(ctx context.Context, arg CreateRowParams) error {
	_, err := q.db.ExecContext(ctx, createRow,
		arg.Name,
		arg.Val,
		arg.Month,
		arg.Year,
	)
	return err
}

const deleteLastRow = `-- name: DeleteLastRow :one
DELETE FROM notes
WHERE id = (SELECT MAX(id) from notes)
RETURNING name, val
`

type DeleteLastRowRow struct {
	Name string
	Val  int64
}

func (q *Queries) DeleteLastRow(ctx context.Context) (DeleteLastRowRow, error) {
	row := q.db.QueryRowContext(ctx, deleteLastRow)
	var i DeleteLastRowRow
	err := row.Scan(&i.Name, &i.Val)
	return i, err
}

const getAllRowsInMonth = `-- name: GetAllRowsInMonth :many
SELECT id, name, val, month, year
FROM notes
WHERE month = ? AND year = ?
`

type GetAllRowsInMonthParams struct {
	Month int64
	Year  int64
}

func (q *Queries) GetAllRowsInMonth(ctx context.Context, arg GetAllRowsInMonthParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getAllRowsInMonth, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Val,
			&i.Month,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvg = `-- name: GetAvg :one
SELECT AVG(val) FROM notes
WHERE name = ? AND month = ? AND year = ?
`

type GetAvgParams struct {
	Name  string
	Month int64
	Year  int64
}

func (q *Queries) GetAvg(ctx context.Context, arg GetAvgParams) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getAvg, arg.Name, arg.Month, arg.Year)
	var avg sql.NullFloat64
	err := row.Scan(&avg)
	return avg, err
}

const getMonthlyTotal = `-- name: GetMonthlyTotal :one
SELECT SUM(val)
FROM notes
WHERE month = ? AND year = ?
`

type GetMonthlyTotalParams struct {
	Month int64
	Year  int64
}

func (q *Queries) GetMonthlyTotal(ctx context.Context, arg GetMonthlyTotalParams) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyTotal, arg.Month, arg.Year)
	var sum sql.NullFloat64
	err := row.Scan(&sum)
	return sum, err
}

const getWifeSalary = `-- name: GetWifeSalary :one
SELECT COUNT(*), SUM(val)
FROM notes
WHERE name = ? AND month = ? AND year = ?
`

type GetWifeSalaryParams struct {
	Name  string
	Month int64
	Year  int64
}

type GetWifeSalaryRow struct {
	Count int64
	Sum   sql.NullFloat64
}

func (q *Queries) GetWifeSalary(ctx context.Context, arg GetWifeSalaryParams) (GetWifeSalaryRow, error) {
	row := q.db.QueryRowContext(ctx, getWifeSalary, arg.Name, arg.Month, arg.Year)
	var i GetWifeSalaryRow
	err := row.Scan(&i.Count, &i.Sum)
	return i, err
}
